#!/bin/bash
#########################################################
# Convert netcdf3 files to compressed netcdf4 files 
# python-netcdf4 module required
# use it as : nc3toznc4 files*
# or
# nc3toznc4 -R path_to_folder/
#
# [J. Gula _ 09/23/14]
#########################################################

[ $# -eq 0 ] && { echo "Usage: $0 list_of_files* or $0 -R path_to_folder "; exit 1; }

###########################################################

REC=0
rm files_to_compress

while getopts ":R" opt; do
  case $opt in
    R)
      let REC=1
      shift $(($OPTIND - 1))
      echo "acting recursively on all .nc files in",  $1
      DIR=$1
      find $DIR/* -type f \( -name "*.nc" \) > files_to_compress
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1
      ;;
  esac
done

###########################################################

[ $# -eq 0 ] && { echo "Usage: $0 list_of_files* or $0 -R path_to_folder "; exit 1; }

###########################################################

if [ $REC = 0 ]; then
    DIR=$(dirname $1)
    for i in $@; do
        echo $i >> files_to_compress
    done
fi

###########################################################
#Log file
COMPRESSED=$DIR/COMPRESSED
###########################################################

date >> $COMPRESSED
echo 'The following filess have been converted to netcdf4 with zlib - using nc3tonc4 (complevel=6)' >> $COMPRESSED

netcdf3='64-bit offset'
netcdf3_classic='classic'
netcdf4='netCDF-4'
netcdf4_classic='netCDF-4 classic model'

trap "exit" INT
#for i in $@; do
for i in `cat files_to_compress`; do
    echo $i
    format=`ncdump -k $i`
    if [ "$format" = "$netcdf3" -o "$format" = "$netcdf3_classic" ]; then
        echo 'format is', $format
        nc3tonc4 -o --chunk=1 --complevel=6 $i $i.znc > $COMPRESSED.log
        check_nc3toznc4 $i $i.znc $COMPRESSED.log
        echo $i >> $COMPRESSED
    fi

done


###########################################################

echo 'All files have been converted to netcdf4 with zlib - using nc3tonc4 (complevel=6)' >> $COMPRESSED
date >> $COMPRESSED




