#!/bin/bash

#0. Setup a python virtual environment
# see Virtual_Python_install

#1. Compile the Fortran modules using f2py [included in numpy module]:

cd Modules
make

#2. Edit the names of your ROMS files and location in "Modules/R_files.py"

vi Modules/R_files.py


