#!/bin/bash
#PBS -q sequentiel
#PBS -l mem=2g
#PBS -l walltime=00:30:00
# -----------------------------------------------------------------
# Jcollin 2023
# 
# user parameters
# -----------------------------------------------------------------
pyticles_env="/home2/datawork/jcollin/conda/envs/pyticles-3.11"
modules_dir="../Modules/"
pyticles_receipe="pyticles_datarmor"

# end of user parameters
#  -----------------------------------------------------------------
cd $PBS_O_WORKDIR
qstat -f $PBS_JOBID
source /usr/share/Modules/3.2.10/init/bash

module purge
module load Bash/4.3_gcc-5.3.0
module load gcc/9.1.0
module load conda/latest

source activate $pyticles_env
cd $modules_dir
make $pyticles_receipe
